[package]
name = "ayran-cli"
version.workspace = true
edition.workspace = true
publish = false
repository = "https://github.com/MLgentDev/ayran"

[package.metadata.dist]
dist = true

[[bin]]
name = "ayran"
path = "src/main.rs"

[dependencies]
axoupdater = { version = "0.9", default-features = false, features = ["blocking", "github_releases", "tls_native_roots"] }
ayran-core = { path = "../ayran-core" }
clap = { version = "4.6", features = ["std", "string"] }
serde_json = "1.0.151"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
toml_edit = "0.25"
sha2 = "0.10"

filetime = "0.2"
serde_yaml = "0.9"
tempfile = "3.27"
serde_json_lenient = "0.2"
semver = "1.0.28"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
rustix = { version = "1.1", features = ["fs"] }
